"""part

Revision ID: 2ef5fb490417
Revises: 9d66840f57dc
Create Date: 2023-12-11 13:42:35.278038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ef5fb490417'
down_revision = '9d66840f57dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('desc', sa.String(length=240), nullable=True),
    sa.Column('img_url', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('part')
    # ### end Alembic commands ###
